[emacs]
name = 'emacs'
restart = false
args = ['--daemon']

[waybar]
name = 'waybar'
restart = false
setenvs = { 'EXAMPLE_ENV_VAR' = 'JEFF', 'EXAMPLE_ENV_VAR_2' = '0' }
args = ['--log-level=critical']

[foot]
name = 'foot'
restart = false
args = ['--server']

[mako]
name = 'mako'
restart = false

[xfsettingsd]
name = 'xfsettingsd'
restart = false
args = ['--replace', '--disable-wm-check', '--daemon']
unsetenvs = ['WAYLAND_DISPLAY']

[sww-daemon]
name = 'swww'
restart = false
args = ['init']

[swww]
name = 'swww'
restart = false
args = ['img', '~/pictures/wallpapers/wall_04.png']